### ISSUE TITLE
A discrete CEM3320 board that doesn't need a CEM3320 would be nice.

### ISSUE THREAD

**Issue by 01GOD** [ImoogDi/1MoreF#1]
Thanks for posting that! A discrete CEM3320 board that doesn't need a CEM3320 would be nice.

**Comment by ImoogDi** [comment]
Building a discrete CEM3320 board isn't as easy as you probably think. Additional it takes a lot of space on board and this is not available.
Anyway, the CEM3320 device is replaced with that common available AS3320.

**Comment by 01GOD** [comment]
> Building a discrete CEM3320 board isn't as easy as you probably think. Additional it takes a lot of space on board and this is not available. Anyway, the CEM3320 device is replaced with that common available AS3320.

Saw now. Had been attacked by some hostile crowds in china (because I am not chinese) and that was sadly and obviously a HUGE hassle. 

Anyway, AS3320 sounds good. I simply like discrete versions of things as an option also sometimes.
